version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "54320:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=client_user
      - POSTGRES_DB=client_db