spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/client
    username: client
    password: client
    driverClassName: org.postgresql.Driver

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

secret: "${JWT_SECRET:secret-key}"